### ISSUE TITLE
Enhancement -- ringperiod resolution

### ISSUE THREAD

**Issue by n8ur** [TAPR/TICC#13]
Not urgent.

Currently, the calculation that determines the ring period has a result that is truncated to integer picosecond.  Since we are multiplying the introduced error by potentially a couple of thousand, it would be good to see if we can improve the precision to 0.1 or 0.01ps.
I think this can be done by the old multiply-then-divide trick in the ringperiod calculation, and combining that into a single statement with the following ringticks \* ringperiod multiplication into the same step.  Final result can be integer picoseconds but want to improve the quality getting there.

**Comment by Tom-McDermott** [comment]
Hi John - Just got back home last night - 8 days with no email access in
Canada (vacation).
Many emails to sort through...

Let me take a look through your code and try to run some off-line
analytical tests.

-- Tom, N5EG

**Comment by Tom-McDermott** [comment]
Found just a few code changes referenced by this issue, but none dealing with
the ring period resolution - The only branch found is master, so the others probably
have already been merged into master.  Perhaps the code changes were lost, or else
they were committed in a previous update.

John - could you point us to the section of code that you changed for this?

-- Tom

**Comment by n8ur** [comment]
We should talk before you get too far... I've encountered a nasty that 
needs to be addressed.  Will be working on it this weekend.  Maybe give 
you a call tonight (remembering time difference) or Saturday?

**Comment by n8ur** [comment]
Have increased precision of calculations, removing a major source of error.  Also added TIME_DILATION constant to allow fine adjustment of normLSB result.
