### ISSUE TITLE
Values to save in eeprom

### ISSUE THREAD

**Issue by n8ur** [TAPR/TICC#20]
We should move as much config as possible from constants, to variables stored in eeprom so the user can change without needing to recompile.  Here's my first pass at var, type length (bytes), index position:

SERIAL                char[11]     0    // board serial number (10 char); can we set once then protect?
CLOCK_HZ             uint32    11    // clock speed -- default 10 000 000
PICTIC_PS             uint32    15    // 100 000 000 for 100us
CAL_PERIODS         uint8    19    // calibration periods
TIME_DILATE_0     uint32    20    // time dilation factor channel 0
TIME_DILATE_1     uint32    24    // time dilation factor channel 1
FIXED_STOP_0      uint32    28    // do we autocal, and if so the stored value
FIXED_STOP_1      uint32    32    // do we autocal, and if so the stored value
FUDGE_0               uint32    36    // fudge factor channel 0
FUDGE_1               uint32    40    // fudge factor channel 1
MODE                      uint8    44    // operating mode

I thought about including firmware version, but we can compile that into the firmware itself by setting it as an array of char[].  No need to store in eeprom then.

**Comment by ghbyrkit** [comment]
John,
You likely want to have an 'eeprom data layout version byte' at the start.  The reason is: you may update the layout by adding things at the end, or deprecating things in the middle.  This way the firmware knows if the eeprom data layout is compatible, needs to be extended, some settings redone, etc.

George

-----Original Message-----

**Comment by n8ur** [comment]
Great idea, George.  I wouldn't have thought of that, but I'm guessing 
you've had some experience in that regard. :-)

**Comment by ghbyrkit** [comment]
Just a little experience in this area...

George

-----Original Message-----

**Comment by n8ur** [comment]
EEPROM config storage is implemented, with version number as suggested by George.
